package application.repository.impl.h2;

import application.model.Article;
import application.repository.ArticleRepository;
import application.repository.rowmapper.SelectArticleRowMapper;
import db.JdbcTemplate;
import application.repository.rowmapper.SelectArticlesRowMapper;
import application.repository.rowmapper.InsertArticleRowMapper;
import db.RowMapper;
import java.util.List;

@SuppressWarnings(value = "unchecked")
public class ArticleH2Database implements ArticleRepository {


    private final RowMapper<List<Article>> articlesRowMapper = new SelectArticlesRowMapper();
    private final RowMapper<Article> articleRowMapper = new SelectArticleRowMapper();
    private final JdbcTemplate jdbcTemplate;

    public ArticleH2Database(JdbcTemplate jdbcTemplate) {
        this.jdbcTemplate = jdbcTemplate;
    }

    @Override
    public Article save(Article article) {
        String sql = """
                    INSERT INTO articles (title, content, user_id)
                    VALUES (?, ?, ?)
                """;
        long generatedKey = jdbcTemplate.executeInsertWithAutoGeneratedKey(
                sql,
                new InsertArticleRowMapper(),
                article.getTitle(),
                article.getContent(),
                article.getUserId()
        );
        return new Article(
                generatedKey,
                article.getTitle(),
                article.getContent(),
                article.getUserId()
        );
    }

    @Override
    public List<Article> findUserById(String userId) {
        String sql = "SELECT * FROM articles WHERE user_id = ?";
        return jdbcTemplate.executeQuery(sql, articlesRowMapper, userId);
    }

    @Override
    public void clear() {
        String sql = "DELETE FROM articles";
        jdbcTemplate.executeUpdate(sql);
    }
}
