package application.repository.impl.h2;

import application.model.Article;
import application.repository.ArticleRepository;
import application.repository.rowmapper.CountArticleRowMapper;
import application.repository.rowmapper.SelectArticleRowMapper;
import db.JdbcTemplate;
import application.repository.rowmapper.SelectArticlesRowMapper;
import application.repository.rowmapper.InsertArticleRowMapper;
import db.RowMapper;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Locale;

@SuppressWarnings(value = "unchecked")
public class ArticleH2Database implements ArticleRepository {


    private final RowMapper<List<Article>> articlesRowMapper = new SelectArticlesRowMapper();
    private final RowMapper<Article> articleRowMapper = new SelectArticleRowMapper();
    private final RowMapper<Integer> countRowMapper = new CountArticleRowMapper();
    private final JdbcTemplate jdbcTemplate;

    public ArticleH2Database(JdbcTemplate jdbcTemplate) {
        this.jdbcTemplate = jdbcTemplate;
    }

    @Override
    public Article save(Article article) {
        LocalDateTime now = LocalDateTime.now();
        String sql = """
                    INSERT INTO articles (title, content, user_id, created_at)
                    VALUES (?, ?, ?, ?)
                """;
        long generatedKey = jdbcTemplate.executeInsertWithAutoGeneratedKey(
                sql,
                new InsertArticleRowMapper(),
                article.getTitle(),
                article.getContent(),
                article.getUserId(),
                now
        );
        return new Article(
                generatedKey,
                article.getTitle(),
                article.getContent(),
                article.getUserId(),
                now
        );
    }

    @Override
    public List<Article> findUserById(String userId) {
        String sql = "SELECT * FROM articles WHERE user_id = ?";
        return jdbcTemplate.executeQuery(sql, articlesRowMapper, userId);
    }

    @Override
    public void clear() {
        String sql = "DELETE FROM articles";
        jdbcTemplate.executeUpdate(sql);
    }

    @Override
    public int count() {
        String sql = "SELECT COUNT(*) FROM articles";
        return jdbcTemplate.executeQuery(sql, countRowMapper);
    }

    @Override
    public Article getLatestArticle(int offset) {
        String sql = "SELECT * FROM articles ORDER BY created_at DESC LIMIT ?";
        return jdbcTemplate.executeQuery(sql, articleRowMapper, offset);
    }
}
