package db.h2;

import application.model.Article;
import application.repository.ArticleRepository;
import db.JdbcTemplate;
import db.SqlRunner;
import db.rowmapper.ArticlesRowMapper;
import db.rowmapper.InsertArticleRowMapper;
import db.rowmapper.RowMapper;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;

@SuppressWarnings(value = "unchecked")
public class ArticleH2Database implements ArticleRepository {

    private final JdbcTemplate jdbcTemplate = new JdbcTemplate();

    @Override
    public Article save(Article article) {
        String sql = """
                    INSERT INTO articles (title, content, user_id)
                    VALUES (?, ?, ?)
                """;
        long generatedKey = jdbcTemplate.executeInsertWithAutoGeneratedKey(
                sql,
                new InsertArticleRowMapper(),
                article.getTitle(),
                article.getContent(),
                article.getUserId()
        );
        return new Article(
                generatedKey,
                article.getTitle(),
                article.getContent(),
                article.getUserId()
        );
    }

    @Override
    public List<Article> findUserById(String userId) {
        String sql = "SELECT * FROM articles WHERE user_id = ?";
        RowMapper<List<Article>> articleRowMapper = new ArticlesRowMapper();
        return jdbcTemplate.executeQuery(sql, articleRowMapper, userId);
    }

    @Override
    public void clear() {
        String sql = "DELETE FROM articles";
        jdbcTemplate.executeUpdate(sql);
    }
}
