package db;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class JdbcTemplate {

    private final Logger logger = LoggerFactory.getLogger(JdbcTemplate.class);

    private final JdbcProperties jdbcProperties;

    public JdbcTemplate(JdbcProperties jdbcProperties) {
        this.jdbcProperties = jdbcProperties;
    }

    public <T> T executeQuery(String sql, RowMapper<T> rowMapper, Object... args) {
        try (Connection conn = DriverManager.getConnection(
                jdbcProperties.url(),
                jdbcProperties.user(),
                jdbcProperties.password()
        );
             PreparedStatement ps = conn.prepareStatement(sql)
        ) {
            for (int i = 0; i < args.length; i++) {
                ps.setObject(i + 1, args[i]);
            }
            logger.info("Executing query: " + sql + " with parameters: " + Arrays.toString(args));
            ResultSet resultSet = ps.executeQuery();
            return rowMapper.mapRow(resultSet);
        } catch (SQLException e) {
            throw new RuntimeException("Error execute Query" + sql, e);
        }
    }

    public int executeUpdate(String sql, Object... args) {
        try (Connection conn = DriverManager.getConnection(
                jdbcProperties.url(),
                jdbcProperties.user(),
                jdbcProperties.password()
        );
             PreparedStatement preparedStatement = conn.prepareStatement(sql)
        ) {
            for (int i = 0; i < args.length; i++) {
                preparedStatement.setObject(i + 1, args[i]);
            }
            logger.info("Executing query: " + sql + " with args: " + Arrays.toString(args));
            return preparedStatement.executeUpdate();
        } catch (SQLException e) {
            throw new RuntimeException("Error execute Update" + sql, e);
        }
    }

    public <T> T executeInsertWithAutoGeneratedKey(String sql, RowMapper<T> rowMapper, Object... args) {
        try (Connection conn = DriverManager.getConnection(
                jdbcProperties.url(),
                jdbcProperties.user(),
                jdbcProperties.password()
        );
             PreparedStatement preparedStatement = conn.prepareStatement(sql, PreparedStatement.RETURN_GENERATED_KEYS)
        ) {
            for (int i = 0; i < args.length; i++) {
                preparedStatement.setObject(i + 1, args[i]);
            }
            preparedStatement.executeUpdate();
            try (ResultSet generatedKeys = preparedStatement.getGeneratedKeys()) {
                return rowMapper.mapRow(generatedKeys);
            }
        } catch (SQLException e) {
            throw new RuntimeException("Error execute Update" + sql, e);
        }
    }
}
